tabetalt/kit

- src/components/Input/Input.stories.tsx
- src/theme.ts
Adds theme configuration for Input Component and stories.
fix #11
> feat(Input): Add Input component

- src/components/Badge/Badge.stories.tsx
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Link/Link.stories.tsx
- src/components/Radio/Radio.stories.tsx
- src/theme.ts
Includes the following PRs for release:
- feat(Badge): Add Badge Component #17 
- feat(Link): Add Link Component #16 
- feat(Radio): Add Radio component #15 
- feat(Checkbox): Add Checkbox component #14
> Release v1.3.0

- src/components/Badge/Badge.stories.tsx
- src/theme.ts
Adds theme configuration for Badge and stories.
fix #9
> feat(Badge): Add Badge Component

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Radio/Radio.stories.tsx
- src/theme.ts
Adds theme configuration for Radio and stories.
fix #7
(Includes #14)
> feat(Radio): Add Radio component

- src/components/Link/Link.stories.tsx
- src/theme.ts
Adds theme configuration for Link and stories.
fix #8
> feat(Link): Add Link Component

- src/components/Checkbox/Checkbox.stories.tsx
- src/theme.ts
Adds theme configuration for Checkbox and stories.
fix #6
> feat(Checkbox): Add Checkbox component

- src/theme/index.ts
- src/theme/styles.ts
- src/theme/theme.stories.tsx
> fix(Typography): Fixes font-sizing according to design specifications

- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
- src/components/Select/Select.stories.tsx
- src/components/util.ts
- src/theme/forms.ts
- feat: Add Select Component
- feat(Field): Add Field component
> feat: Add Field component

- src/components/Select/Select.stories.tsx
- src/theme/forms.ts
> feat: Add Select Component

- package.json
- src/components/Field/Field.stories.tsx
- src/components/Field/Field.tsx
- src/components/LoaderButton/LoaderButton.stories.tsx
- src/components/LoaderButton/LoaderButton.tsx
- src/components/LoaderIcon/LoaderIcon.stories.tsx
- src/components/LoaderIcon/LoaderIcon.tsx
- src/components/index.ts
- yarn.lock
> feat: Add LoaderButton and LoaderIcon

- package.json
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/index.ts
- yarn.lock
We will extend this with more features. ref #41
fix #42
fix tabetalt/admin#34
> feat: Add basic Table component

- package.json
- src/components/CloseButton/CloseButton.stories.tsx
- src/components/CloseButton/CloseButton.tsx
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/components/index.ts
- src/theme/index.ts
- yarn.lock
@cobraz I'm not sure about the exact styles, need  sources
closes #48
> feat(Components): Added basic Modal component

- .eslintrc.json
- package.json
- yarn.lock
@cobraz actually, you are right, eslint already added
just added npm script  and commit hook
> dev(eslint): Added lint command and commit hook

- src/theme/styles.ts
> fix(Header): Added header margin bottom. Fixed header font sizes

- package.json
- src/components/InputTags/InputTags.stories.tsx
- src/components/InputTags/InputTags.tsx
- src/components/InputTags/styles.ts
- src/components/InputTags/types.ts
- src/components/index.ts
- src/types/index.d.ts
- yarn.lock
> feat(Components): Added InputTags component

- src/components/CheckboxList/CheckboxList.stories.tsx
- src/components/CheckboxList/CheckboxList.tsx
- src/components/CheckboxList/checkbox-list-props.ts
- src/components/Editor/Editor.stories.tsx
- src/components/Editor/Editor.tsx
> feat(CheckboxList): Added checkbox list component

- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/Switch/switch-props.tsx
> feat(Switch): Added switch component

- package.json
- src/components/CheckboxList/CheckboxList.tsx
- src/components/LoaderButton/LoaderButton.stories.tsx
- src/components/LoaderButton/LoaderButton.tsx
- src/components/OptionView/OptionView.stories.tsx
- src/components/OptionView/OptionView.tsx
- src/components/OptionView/option-view-props.ts
- src/components/index.ts
Added base view with ability for showing data inside it
Close #60
> feat(OptionView): Added view for selecting option

- src/components/Editor/style.ts
> fix(editor): fixed editor border color

- package.json
- src/components/Editor/Editor.stories.tsx
- src/components/Editor/Editor.tsx
- src/components/Editor/deserializeHTML.tsx
- src/components/Editor/serializeHTML.tsx
- yarn.lock
Added html serialization
Added html deserialisation
re tabetalt/api#84
> fix(editor-serialize-text): added parsing html text for editor

- src/components/Editor/Editor.stories.tsx
- src/components/Editor/Editor.tsx
- src/components/Editor/serializeHTML.tsx
- src/components/InputTags/InputTags.tsx
> fix(editor-inputTag): added default value for editor.
